buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.parchmentmc.org' }
        maven { url = 'https://plugins.gradle.org/m2/' }
        maven { url = 'https://maven.firstdark.dev/releases' }
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
        classpath 'org.parchmentmc:librarian:1.+'
        classpath 'com.hypherionmc.modutils:modpublisher:2.0.4'
    }
}

apply plugin: 'com.hypherionmc.modutils.modpublisher'
apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.parchmentmc.librarian.forgegradle'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'
if (project.file('../gradletools.gradle').exists()) {
    apply from: '../gradletools.gradle'
} else {
    apply from: 'https://raw.githubusercontent.com/McJtyMods/MultiWorkspace/1.20_tech/gradletools.gradle'
}

group= "com.github.mcjty"
archivesBaseName = "incontrol"
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repos()
repositories {
    maven {
        url = "https://maven.saps.dev/releases"
        content {
            includeGroup "dev.latvian.mods"
        }
    }
}
runs('incontrol')
jars('incontrol')

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

dependencies {
    mc()
    jei()
    top()
    lostcities()
    gamestages()
    sereneseasons()
    compileOnly("dev.latvian.mods:kubejs-forge:2001.6.5-build.26") {
        transitive = false
    }
    implementation fg.deobf("curse.maven:customnpcs-unofficial-1052708:6866598")
    testImplementation "org.junit.jupiter:junit-jupiter:5.10.2"
}

test {
    useJUnitPlatform()
}

modpublisher(['game-stages', 'the-lost-cities'], [], ['the-lost-cities'], [], [])
