buildscript {
    repositories {
        maven { url = 'https://maven.firstdark.dev/releases' }
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.hypherionmc.modutils:modpublisher:2.2.1'
    }
}

plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.4'
}

apply plugin: 'com.hypherionmc.modutils.modpublisher'

if (project.file('../gradletools.gradle').exists()) {
    apply from: '../gradletools.gradle'
} else {
    apply from: 'https://raw.githubusercontent.com/McJtyMods/MultiWorkspace/1.21_neo/gradletools.gradle'
}

group= "com.github.mcjty"
archivesBaseName = "incontrol"
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repos()
runs()
jars()

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

dependencies {
    mc()
    jei()
    top()
    lostcities()
//    gamestages()
    sereneseasons()
    implementation "curse.maven:customnpcs-unofficial-1052708:7005944"
}

modpublisher(['game-stages', 'the-lost-cities'], [], ['the-lost-cities'], [], [])

subsystems {
    parchment {
        minecraftVersion = "${parchment_minecraft_version}"
        mappingsVersion = "${parchment_version}"
    }
}
