buildscript {
    repositories {
        maven { url = 'https://maven.firstdark.dev/releases' }
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.hypherionmc.modutils:modpublisher:2.2.1'
    }
}

plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.4'
}

apply plugin: 'com.hypherionmc.modutils.modpublisher'

if (project.file('../gradletools.gradle').exists()) {
    apply from: '../gradletools.gradle'
} else {
    apply from: 'https://raw.githubusercontent.com/McJtyMods/MultiWorkspace/1.21_neo/gradletools.gradle'
}

group= "com.github.mcjty"
archivesBaseName = "incontrol"
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repos()
repositories {
    maven {
        url = "https://maven.saps.dev/releases"
        content {
            includeGroup "dev.latvian.mods"
        }
    }
}
runs()
jars()

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

dependencies {
    mc()
    jei()
    top()
    lostcities()
//    gamestages()
    sereneseasons()
    compileOnly("dev.latvian.mods:kubejs-neoforge:2101.7.2-build.303") {
        transitive = false
    }
    implementation "curse.maven:customnpcs-unofficial-1052708:7005944"
    testImplementation "org.junit.jupiter:junit-jupiter:5.10.2"
}

test {
    useJUnitPlatform()
}

modpublisher(['game-stages', 'the-lost-cities'], [], ['the-lost-cities'], [], [])

subsystems {
    parchment {
        minecraftVersion = "${parchment_minecraft_version}"
        mappingsVersion = "${parchment_version}"
    }
}
