modLoader="javafml"
loaderVersion="[2,)"
license="MIT License https://github.com/McJtyMods/InControl/blob/1.21_neo/LICENSE"
issueTrackerURL="http://github.com/McJtyMods/InControl/issues"
displayURL="http://github.com/McJtyMods/InControl/"
authors="McJty"

[[mods]]
modId="incontrol"
version="${file.jarVersion}"
displayName="InControl"
#updateJSONURL="http://myurl.me/" #optional
description='''
Be in control of spawns
'''
[[dependencies.incontrol]]
    modId="neoforge"
    type="required"
    versionRange="[21.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.incontrol]]
    modId="lostcities"
    type="optional"
    versionRange="[1.21-8.2.1,)"
    ordering="NONE"
    side="BOTH"
